stages:
  data_ingestion:
    cmd: python src/components/data_ingestion.py
    deps:
    - src/components/data_ingestion.py
    params:
    - data_ingestion.splitting_ratio
    outs:
    - data/raw

  data_transformation:
    cmd: python src/components/data_transformation.py
    deps:
    - data/raw
    - src/components/data_transformation.py
    params:
    - data_transformation.n_steps
    outs:
    - data/transformed
  
  model_training:
    cmd: python src/components/model_training.py
    deps:
    - data/transformed
    - src/components/model_training.py
    params:
    - model_training.lstm_units
    - model_training.dropout_ratio
    - model_training.dense_units
    - model_training.learning_rate
    - model_training.epochs
    - model_training.batch_size
    - model_training.patience
    - model_training.optimizer
    - model_training.model_config
    outs:
    - models/model/lstm_model.h5

  model_evaluation:
    cmd: python src/components/model_evaluation.py
    deps:
    - models/model/lstm_model.h5
    - data/transformed
    - src/components/model_evaluation.py
    outs:
    - evaluation/metrics.json